influxdb:
    build: ./influxdb
    restart: always
    volumes:
        - ./data/influxdb:/data
    ports:
        - "8083:8083"
        - "8086:8086"
statsd:
    build: ./statsd
    environment:
        INFLUXDB_USER: root
        INFLUXDB_PASS: ${INFLUXDB_PASS}
    ports:
        - "8125:8125/udp"
    links:
        - influxdb
grafana:
    build: ./grafana
    ports:
        - "80:80"
    links:
        - influxdb
    volumes:
        - ./data/grafana:/data
